### ISSUE TITLE
Fix Headers

### ISSUE THREAD

**Issue by YamazakiYasuhiro** [jtf-2016/jtf-2016.github.io#106]
This request comes from a Google spread sheet created by Yamaguchi-san.

> 全ページのフッター
> コピーライト表示の「July TechFesta 2016実行委員会」を「July Tech Festa 2016実行委員会」に修正（Techの後に半角スペース）

**Comment by koudaiii** [comment]
Header ? or Footer ?

**Comment by koudaiii** [comment]
Merged
