### ISSUE TITLE
Inside links

### ISSUE THREAD

**Issue by YamazakiYasuhiro** [jtf-2016/jtf-2016.github.io#108]
This request comes from a Google spread sheet created by Yamaguchi-san.

> ACCESSへのページ内リンクを設定できないか？（スポンサー等に会場を連絡する時にURLを貼りたい。去年はhttp://2015.techfesta.jp/p/access.html）

**Comment by koudaiii** [comment]
Just an idea

http://2016.techfest.jp/#access

![image](https://cloud.githubusercontent.com/assets/2929102/15394969/bdf7e68e-1e10-11e6-9447-60d72956c955.png)

What do you think?? @YamazakiYasuhiro
