### ISSUE TITLE
Be difference size for each sponsor's logo

### ISSUE THREAD

**Issue by YamazakiYasuhiro** [jtf-2016/jtf-2016.github.io#111]
This request comes from a Google spread sheet created by Yamaguchi-san.

> スポンサーロゴサイズを調整してください。上位スポンサーほど大きくなるように。

**Comment by YamazakiYasuhiro** [comment]
横幅を3等分しロゴを収める箱とします。
それぞれの幅を100%としたとき、下記のロゴ画像サイズを指定します。
- Wood: 100%
- Platinum: 90%
- Gold: 80%
- Silver: 60%
- Mono: 60%
- 後援: 60%

**Comment by koudaiii** [comment]
:+1:
